### ISSUE TITLE
Windows Specific Implementation of Setting the Foreground Window

### ISSUE THREAD

**Issue by shujaatak** [itay-grudev/SingleApplication#107]
Can you please provide a quick simple example of windows specific implementation of setting the foreground window? 

I am having hard time following the instructions found here: https://github.com/itay-grudev/SingleApplication/blob/master/Windows.md

Best regards

**Comment by itay-grudev** [comment]
```cpp
// main.cpp

int main( int argc, char* argv[] )
    SingleApplication app( argc, argv );

    if( app.isSecondary() ) {
        // This API requires LIBS += User32.lib to be added to the project
        AllowSetForegroundWindow( DWORD( app.primaryPid() ) );
    }

    MyMainQtCode* myApp = new MyMainQtCode();
    
    if( app.isPrimary() ) {
        QObject::connect(
            &app, &SingleApplication::instanceStarted,
            myApp, &App::instanceStarted
        );
    }
}
```

```cpp
// app.cpp

MyMainQtCode::MyMainQtCode() {
  myMainWindow = new QWindow(); // or a QWidget
}

void MyMainQtCode::instanceStarted() {
    QApplication::setActiveWindow( myMainWindow );
}
```

**Comment by itay-grudev** [comment]
I hope it worked. I didn't have time to test it. Have a nice day @shujaatak!

**Comment by benma** [comment]
@itay-grudev fyi, you don't need all of this and you can simply call:

`QWindowsWindowFunctions::setWindowActivationBehavior(QWindowsWindowFunctions::AlwaysActivateWindow);` which does all the magic to make it work on Windows.

See https://github.com/digitalbitbox/bitbox-wallet-app/pull/1346/ for reference.

**Comment by itay-grudev** [comment]
This library does a lot more than just dual instance protection.

**Comment by benma** [comment]
@itay-grudev sorry I meant only the part this issue refers to - bringing the app to the foreground on Windows.

`        AllowSetForegroundWindow( DWORD( app.primaryPid() ) );` , User32, etc. is not needed, `QWindowsWindowFunctions::setWindowActivationBehavior(QWindowsWindowFunctions::AlwaysActivateWindow);` takes care of all of that. It was a lot simpler for me to make it work this way versus the way it is documented. Since it is an official function supported by Qt, it is also likely a more robust solution.

I meant this doc to be updated with this info:

https://github.com/itay-grudev/SingleApplication/blob/master/Windows.md

**Comment by itay-grudev** [comment]
Yhea, I got that.
