### ISSUE TITLE
exited with code 134

### ISSUE THREAD

**Issue by gcala** [itay-grudev/SingleApplication#42]
Hi, I'm trying to integrate your code in my application.

I inserted in .pro file:
```
DEFINES += QT_DEPRECATED_WARNINGS QAPPLICATION_CLASS=QGuiApplication
include(singleapplication/singleapplication.pri)
```
and my main.cpp looks like:
```
#include "mainwindow.h"
#include <QApplication>
#include <singleapplication.h>

int main(int argc, char *argv[])
{
    SingleApplication app(argc, argv);

    MainWindow w;

    QObject::connect( &app, &SingleApplication::instanceStarted, [ &w ]() {
            w.raise();
            w.activateWindow();
    });

    w.show();

    return app.exec();
}
```

But the application FC at launch with the above error and debugger pointing to mainwindow.cpp:
```
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow) // <----- GDB stops here
{
    ui->setupUi(this);
    ....
```
Do you have any idea about the issue? Thanks for your time.

**Comment by itay-grudev** [comment]
I'm sorry for the late response. I suspect the problem is in your Window class. SingleApplication handles unix signals and to give you information on what really happened returns `128 + signum`. Meaning that code `134` = `6` (SIGABRT). See the **Implementation** notes in the [README](https://github.com/itay-grudev/SingleApplication#implementation).
